# SQL

## CREATE 

The general syntax to create a table: 
```{sql, eval = FALSE}
create table TABLENAME (
  COLUMN1 datatype, 
  COLUMN2 datatype, 
  COLUMN3 datatype, 
  ... );
```


To create a table called `TEST` with two columns - `ID` of type integer, and `NAME` of type varchar, we could create it using the following SQL statement:

```{sql, eval = FALSE}
create table TEST(
  ID int
  NAME varchar(30)
);
```

To create a table called `COUNTRY` with an `ID` column, a two letter country code column `CCODE`, and a variable length country name column `NAME`:

```{sql, eval = FALSE}
create table COUNTRY(
    ID int,
    CCODE char(2),
    NAME varchar(60)
);
```

Sometimes you may see additional keywords in a create table statement:

```{sql, eval = FALSE}
create table COUNTRY(
    ID int NOT NULL,
    CCODE char(2),
    NAME varchar(60),
    PRIMARY KEY(ID)
);
```


- In the above example the `ID` column has the <span style="color:blue">**`NOT NULL`**</span>  constraint added after the datatype - meaning that *it cannot contain a NULL or an empty value*. 

- If you look at the last row in the create table statement above you will note that we are using `ID` as a <span style="color:blue">**Primary Key**</span>  and the database **does not allow** Primary Keys to have **`NULL`** values. *A Primary Key is a unique identifier in a table, and using Primary Keys can help speed up your queries significantly*. 

- If the table you are trying to create already exists in the database, you will get an error indicating table `XXX.YYY` already exists. To circumvent this error, either create a table with a different name or first `DROP` the existing table. It is quite common to issue a `DROP` before doing a `CREATE` in test and development scenarios. 

## DROP 

The general syntax to drop a table: 
```{sql, eval = FALSE}
drop table TABLENAME;
```

For example, to drop the table COUNTRY, we can use the following code:

```{sql, eval = FALSE}
drop table COUNTRY;
```

## ALTER

```{sql, eval = FALSE}
ALTER TABLE table_name
ADD COLUMN column_name data_type column_constraint;

ALTER TABLE table_name
DROP COLUMN column_name;

ALTER TABLE table_name
ALTER COLUMN column_name SET DATA TYPE data_type;

ALTER TABLE table_name
RENAME COLUMN current_column_name TO new_column_name;
```

## TRUNCATE

```{sql, eval = FALSE}
TRUNCATE TABLE table_name;
```

## Guided Exercise: Create table and insert data

You will to create two tables

1. `PETSALE` 

2. `PET`. 


```{sql, eval = FALSE}
CREATE TABLE PETSALE (
    ID INTEGER NOT NULL,
    PET CHAR(20),
    SALEPRICE DECIMAL(6,2),
    PROFIT DECIMAL(6,2),
    SALEDATE DATE
    );
    
CREATE TABLE PET (
    ID INTEGER NOT NULL,
    ANIMAL VARCHAR(20),
    QUANTITY INTEGER
    );
```

<span style="color:blue">*Now insert some records into the two newly created tables and show all the records of the two tables. *</span>



```{sql, eval = FALSE}
INSERT INTO PETSALE VALUES
    (1,'Cat',450.09,100.47,'2018-05-29'),
    (2,'Dog',666.66,150.76,'2018-06-01'),
    (3,'Parrot',50.00,8.9,'2018-06-04'),
    (4,'Hamster',60.60,12,'2018-06-11'),
    (5,'Goldfish',48.48,3.5,'2018-06-14');
    
INSERT INTO PET VALUES
    (1,'Cat',3),
    (2,'Dog',4),
    (3,'Hamster',2);
    
SELECT * FROM PETSALE;
SELECT * FROM PET;
```


## Guided Exercise: Use the `ALTER` statement to add, delete, or modify columns in two of the existing tables created in the previous exercise.


<span style="color:blue">*Add a new `QUANTITY` column to the `PETSALE` table and show the altered table.*</span>

```{sql, eval = FALSE}
ALTER TABLE PETSALE
ADD COLUMN QUANTITY INTEGER;

SELECT * FROM PETSALE;
```


<span style="color:blue">*Now update the newly added `QUANTITY` column of the `PETSALE` table with some values and show all the records of the table.
*</span>

```{sql, eval = FALSE}
UPDATE PETSALE SET QUANTITY = 9 WHERE ID = 1;
UPDATE PETSALE SET QUANTITY = 3 WHERE ID = 2;
UPDATE PETSALE SET QUANTITY = 2 WHERE ID = 3;
UPDATE PETSALE SET QUANTITY = 6 WHERE ID = 4;
UPDATE PETSALE SET QUANTITY = 24 WHERE ID = 5;

SELECT * FROM PETSALE;
```


<span style="color:blue">*Delete the `PROFIT` column from the `PETSALE` table and show the altered table.
*</span>

```{sql, eval = FALSE}
ALTER TABLE PETSALE
DROP COLUMN PROFIT;

SELECT * FROM PETSALE;
```

<span style="color:blue">*Change the data type to `VARCHAR(20)` type of the column `PET` of the table `PETSALE` and show the altered table. 
*</span>

```{sql, eval = FALSE}
ALTER TABLE PETSALE
ALTER COLUMN PET SET DATA TYPE VARCHAR(20);

SELECT * FROM PETSALE;
```

If you are using IBM db2:
Now verify if the data type of the column PET of the table PETSALE changed to `VARCHAR(20)` type or not. Click on the 3 bar menu icon in the top left corner and click Explore > Tables. Find the `PETSALE` table from Schemas by clicking Select All. Click on the `PETSALE` table to open the Table Definition page of the table. Here, you can see all the current data type of the columns of the `PETSALE` table.

<span style="color:blue">*Rename the column PET to ANIMAL of the PETSALE table and show the altered table.
*</span>

```{sql, eval = FALSE}
ALTER TABLE PETSALE
RENAME COLUMN PET TO ANIMAL;

SELECT * FROM PETSALE;
```


## Guided Exercise: TRUNCATE

In this exercise, you will use the `TRUNCATE` statement to remove all rows from an existing table created in exercise 1 without deleting the table itself.

<span style="color:blue">*Remove all rows from the PET table and show the empty table.
*</span>

```{sql, eval = FALSE}
TRUNCATE TABLE PET IMMEDIATE;
SELECT * FROM PET;
```

## Guided Exercise: DROP

In this exercise, you will use the `DROP` statement to delete an existing table created in the previous exercise.

<span style="color:blue">*Delete the PET table and verify if the table still exists or not (SELECT statement won't work if a table doesn't exist).
*</span>

```{sql, eval = FALSE}
DROP TABLE PET;
SELECT * FROM PET;
```



